import asyncio
import hashlib
from datetime import date, datetime

from db import AsyncSessionLocal, Base, engine
from models import Listing

LISTINGS = [
    dict(source="seed", source_id="1", source_url="https://example.com/1",
         title="Helles 2-Zimmer in Zürich Wiedikon", description="Möbliertes Zimmer, Zwischenmiete Juli–August.",
         price_chf=1800, rooms=2.0, city="Zürich", zip_code="8003", address="Wiedikon",
         area_m2=52, is_furnished=True, gender_preference="female", is_sublet=True,
         available_from=date(2026, 7, 1), available_to=date(2026, 8, 31),
         min_stay_days=30, max_stay_days=62),
    dict(source="seed", source_id="2", source_url="https://example.com/2",
         title="WG-Zimmer Langstrasse, unmöbliert", description="Frauen-WG, ruhige Lage nahe Helvetiaplatz.",
         price_chf=950, rooms=1.0, city="Zürich", zip_code="8004", address="Langstrasse",
         area_m2=18, is_furnished=False, gender_preference="female", is_sublet=False,
         available_from=date(2026, 6, 1), available_to=None,
         min_stay_days=90, max_stay_days=None),
    dict(source="seed", source_id="3", source_url="https://example.com/3",
         title="Modernes Studio Oerlikon", description="Furnished studio, sublet welcome.",
         price_chf=1650, rooms=1.0, city="Zürich", zip_code="8050", address="Oerlikon",
         area_m2=30, is_furnished=True, gender_preference=None, is_sublet=True,
         available_from=date(2026, 7, 15), available_to=date(2026, 9, 15),
         min_stay_days=30, max_stay_days=62),
    dict(source="seed", source_id="4", source_url="https://example.com/4",
         title="3.5-Zimmer Wohnung Seefeld", description="Grosse Wohnung mit Seesicht, möbliert.",
         price_chf=3200, rooms=3.5, city="Zürich", zip_code="8008", address="Seefeld",
         area_m2=90, is_furnished=True, gender_preference=None, is_sublet=False,
         available_from=date(2026, 8, 1), available_to=None,
         min_stay_days=365, max_stay_days=None),
    dict(source="seed", source_id="5", source_url="https://example.com/5",
         title="WG-Zimmer Männer-WG Höngg", description="Männer-WG, 3er WG, unmöbliert.",
         price_chf=850, rooms=1.0, city="Zürich", zip_code="8049", address="Höngg",
         area_m2=16, is_furnished=False, gender_preference="male", is_sublet=False,
         available_from=date(2026, 6, 15), available_to=None,
         min_stay_days=180, max_stay_days=None),
    dict(source="seed", source_id="6", source_url="https://example.com/6",
         title="1.5-Zimmer Altbau Aussersihl", description="Unmöbliert, Mindestmietdauer 1 Jahr.",
         price_chf=1400, rooms=1.5, city="Zürich", zip_code="8004", address="Aussersihl",
         area_m2=40, is_furnished=False, gender_preference=None, is_sublet=False,
         available_from=date(2026, 7, 1), available_to=None,
         min_stay_days=365, max_stay_days=None),
    dict(source="seed", source_id="7", source_url="https://example.com/7",
         title="Untermiete August Altstetten", description="Untermiete, möbliert, nur August.",
         price_chf=1200, rooms=2.0, city="Zürich", zip_code="8048", address="Altstetten",
         area_m2=55, is_furnished=True, gender_preference=None, is_sublet=True,
         available_from=date(2026, 8, 1), available_to=date(2026, 8, 31),
         min_stay_days=28, max_stay_days=31),
    dict(source="seed", source_id="8", source_url="https://example.com/8",
         title="Ruhiges Zimmer Wipkingen", description="Gemischte WG, möbliertes Zimmer.",
         price_chf=1050, rooms=1.0, city="Zürich", zip_code="8037", address="Wipkingen",
         area_m2=20, is_furnished=True, gender_preference=None, is_sublet=False,
         available_from=date(2026, 6, 1), available_to=None,
         min_stay_days=90, max_stay_days=None),
    dict(source="seed", source_id="9", source_url="https://example.com/9",
         title="4-Zimmer Familenwohnung Schwamendingen", description="Grosse Wohnung, unmöbliert.",
         price_chf=2400, rooms=4.0, city="Zürich", zip_code="8051", address="Schwamendingen",
         area_m2=100, is_furnished=False, gender_preference=None, is_sublet=False,
         available_from=date(2026, 9, 1), available_to=None,
         min_stay_days=365, max_stay_days=None),
    dict(source="seed", source_id="10", source_url="https://example.com/10",
         title="Furnished room Zürich University area", description="Female only, furnished, short stay ok.",
         price_chf=1100, rooms=1.0, city="Zürich", zip_code="8006", address="Universitätsviertel",
         area_m2=22, is_furnished=True, gender_preference="female", is_sublet=True,
         available_from=date(2026, 7, 1), available_to=date(2026, 9, 30),
         min_stay_days=30, max_stay_days=92),
    dict(source="seed", source_id="11", source_url="https://example.com/11",
         title="2.5-Zimmer Wohnung Winterthur Zentrum", description="Unmöbliert, ruhige Lage.",
         price_chf=1550, rooms=2.5, city="Winterthur", zip_code="8400", address="Zentrum",
         area_m2=62, is_furnished=False, gender_preference=None, is_sublet=False,
         available_from=date(2026, 7, 1), available_to=None,
         min_stay_days=365, max_stay_days=None),
    dict(source="seed", source_id="12", source_url="https://example.com/12",
         title="WG-Zimmer Winterthur Töss", description="Gemischte WG, möbliert.",
         price_chf=780, rooms=1.0, city="Winterthur", zip_code="8406", address="Töss",
         area_m2=17, is_furnished=True, gender_preference=None, is_sublet=False,
         available_from=date(2026, 6, 1), available_to=None,
         min_stay_days=90, max_stay_days=None),
    dict(source="seed", source_id="13", source_url="https://example.com/13",
         title="Studio Zug Altstadt", description="Furnished studio, sublet July–September.",
         price_chf=1900, rooms=1.0, city="Zug", zip_code="6300", address="Altstadt",
         area_m2=28, is_furnished=True, gender_preference=None, is_sublet=True,
         available_from=date(2026, 7, 1), available_to=date(2026, 9, 30),
         min_stay_days=30, max_stay_days=92),
    dict(source="seed", source_id="14", source_url="https://example.com/14",
         title="3-Zimmer Wohnung Zürich Enge", description="Möbliert, Zwischenmiete ab Juli.",
         price_chf=2800, rooms=3.0, city="Zürich", zip_code="8002", address="Enge",
         area_m2=78, is_furnished=True, gender_preference=None, is_sublet=True,
         available_from=date(2026, 7, 1), available_to=date(2026, 10, 31),
         min_stay_days=60, max_stay_days=123),
    dict(source="seed", source_id="15", source_url="https://example.com/15",
         title="Günstiges Zimmer Zürich Nord", description="Frauen-WG, unmöbliert, Langzeitmiete.",
         price_chf=790, rooms=1.0, city="Zürich", zip_code="8057", address="Zürich Nord",
         area_m2=14, is_furnished=False, gender_preference="female", is_sublet=False,
         available_from=date(2026, 6, 1), available_to=None,
         min_stay_days=180, max_stay_days=None),
    dict(source="seed", source_id="16", source_url="https://example.com/16",
         title="Luxus-Penthouse Zürich Seefeld", description="Möbliert, kurze Untermiete möglich.",
         price_chf=5500, rooms=4.5, city="Zürich", zip_code="8008", address="Seefeld",
         area_m2=160, is_furnished=True, gender_preference=None, is_sublet=True,
         available_from=date(2026, 8, 1), available_to=date(2026, 8, 31),
         min_stay_days=28, max_stay_days=31),
    dict(source="seed", source_id="17", source_url="https://example.com/17",
         title="2-Zimmer Wohnung Baden", description="Unmöbliert, 20min nach Zürich.",
         price_chf=1350, rooms=2.0, city="Baden", zip_code="5400", address="Zentrum",
         area_m2=58, is_furnished=False, gender_preference=None, is_sublet=False,
         available_from=date(2026, 7, 1), available_to=None,
         min_stay_days=365, max_stay_days=None),
    dict(source="seed", source_id="18", source_url="https://example.com/18",
         title="WG-Zimmer Zürich Hürlimann Areal", description="Mixed WG, furnished, sublet ok.",
         price_chf=1250, rooms=1.0, city="Zürich", zip_code="8002", address="Hürlimann Areal",
         area_m2=24, is_furnished=True, gender_preference=None, is_sublet=True,
         available_from=date(2026, 7, 15), available_to=date(2026, 9, 15),
         min_stay_days=30, max_stay_days=62),
    dict(source="seed", source_id="19", source_url="https://example.com/19",
         title="1.5-Zimmer Wohnung Schlieren", description="Unmöbliert, günstig, ÖV-Nähe.",
         price_chf=1150, rooms=1.5, city="Schlieren", zip_code="8952", address="Zentrum",
         area_m2=38, is_furnished=False, gender_preference=None, is_sublet=False,
         available_from=date(2026, 6, 15), available_to=None,
         min_stay_days=365, max_stay_days=None),
    dict(source="seed", source_id="20", source_url="https://example.com/20",
         title="Grosses Zimmer Zürich Wiedikon WG", description="3er WG, möbliert, suchen Mitbewohnerin.",
         price_chf=1300, rooms=1.0, city="Zürich", zip_code="8003", address="Wiedikon",
         area_m2=25, is_furnished=True, gender_preference="female", is_sublet=False,
         available_from=date(2026, 6, 1), available_to=None,
         min_stay_days=90, max_stay_days=None),
]


async def seed():
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    now = datetime.utcnow()
    async with AsyncSessionLocal() as db:
        for data in LISTINGS:
            listing_id = hashlib.sha256(f"{data['source']}{data['source_id']}".encode()).hexdigest()
            listing = Listing(
                id=listing_id,
                first_seen=now,
                last_seen=now,
                latitude=None,
                longitude=None,
                **data,
            )
            db.add(listing)
        await db.commit()
    print(f"Seeded {len(LISTINGS)} listings.")


if __name__ == "__main__":
    asyncio.run(seed())
